name: Release Pest++
on:
  workflow_call:
    inputs:
      branch:
        description: 'Branch to release from.'
        required: true
        type: string
      version:
        description: 'Release version number.'
        required: true
        type: string
env:
  PIXI_BETA_WARNING_OFF: true
jobs:
  build:
    name: Build ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, macos-13, macos-14, windows-2022]
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: Checkout modflow6
        uses: actions/checkout@v5
        with:
          repository: usgs/pestpp
          ref: ${{ inputs.branch }}

      - name: Setup pixi
        uses: prefix-dev/setup-pixi@v0.9.0
        with:
          pixi-version: v0.41.4

      - name: Setup windows compiler
        if: runner.os == 'Windows'
        uses: ilammy/msvc-dev-cmd@v1

      - name: Set env vars
        run: |
          echo "VERSION=${{ inputs.version }}" >> "$GITHUB_ENV"
          ostag=$(python -c "from modflow_devtools.ostags import get_ostag; print(get_ostag())")
          echo "OSTAG=$ostag" >> $GITHUB_ENV

      - name: Build binaries
        run: |
          pixi run configure
          pixi run build-release

      - name: Make distribution
        run: |
          path=pestpp-$VERSION-$OSTAG
          mkdir -p $path
          cp -r bin $path

      - name: Upload distribution
        uses: actions/upload-artifact@v4
        with:
          name: pestpp-$VERSION-$OSTAG
          path: pestpp-$VERSION-$OSTAG
